#!/bin/bash

SAAS_BIN=sass
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
INPUT_PATH=$DIR/../code/media/koowa/com_koowa/scss
OUTPUT_PATH=$DIR/../code/media/koowa/com_koowa/css
FILES=('koowa')

for FILE in "${FILES[@]}"
do
  $SAAS_BIN --sourcemap --style compressed $INPUT_PATH/$FILE.scss $OUTPUT_PATH/$FILE.css
done