#!/bin/bash

LESSC_BIN=lessc
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
INPUT_PATH=$DIR/../code/media/koowa/com_koowa/less
OUTPUT_PATH=$DIR/../code/media/koowa/com_koowa/css
FILES=('datepicker' 'modal' 'select2' 'tree' 'icons' 'template')

for FILE in "${FILES[@]}"
do
  $LESSC_BIN --verbose $INPUT_PATH/$FILE.less $OUTPUT_PATH/$FILE.css -compress
done