#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
JS_PATH=$DIR/../code/resources/assets/js
FILES=('kodekit' 'kodekit.tree' 'kodekit.overlay')

for FILE in ${FILES[@]}
do
  cat $JS_PATH/$FILE.js | uglifyjs -o $JS_PATH/$FILE.min.js
done
