#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
JS_PATH=$DIR/../assets/js
FILES=('koowa' 'koowa.tree' 'koowa.overlay')

for FILE in ${FILES[@]}
do
  cat $JS_PATH/$FILE.js | uglifyjs -o $JS_PATH/$FILE.min.js
done